---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuma-data
  namespace: kuma
spec:
  accessModes:
    - ReadWriteOnce
      resources:
    requests:
      storage: 1Gi
      
      
      
