---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cchoolx-xyz
  namespace: default
spec:
  secretName: pro-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  #commonName: "cchoolx.xyz"
  dnsNames:
    - "*.cchoolx.xyz"