---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cchoolx-stag 
  namespace: default
spec:
  secretName: p-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  #commonName: "*.localhost"
  dnsNames:
  - "*e.localhost"
  - "*.localhost"
