apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
data:
  init-script.js: |-
    db.createUser({
      user: "unifi",      
      pwd: "unifi",   
      roles: [
        { role: "readWrite", db: "unifi" } 
      ]
    });