apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: network
  name: mongodb-pv-claim
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi